// Users
###
POST http://localhost:8090/user/new
content-type:application/json

{
    "username":"super",
    "password":"super",
    "role":"super"
}

###
POST http://localhost:8090/user/login
content-type:application/json

{
    "username":"aditya",
    "password":"aditya"   
}


//End of USER

//Platforms
###
POST http://localhost:8090/platform/add
content-type: application/json

{
    "station_name":"Lucknow",
    "station_code":"LKO"
}

###
PUT http://localhost:8090/platform/modify/65c8a093199c9e67148e089d
content-type: application/json

{
    "station_name":"Deoria",
    "station_code":"DEOS"
}
###
GET http://localhost:8090/platform/getAll
###
GET http://localhost:8090/platform/getById/65c8a093199c9e67148e089d
###
DELETE http://localhost:8090/platform/delete/65c8a093199c9e67148e089d
###
//End Of Platforms

//Assets

###
POST http://localhost:8090/asset/add
content-type: application/json

{
    "asset_code": "ast9999",
    "asset_name": "Water Cooler",
    "description": "Voltas Water Cooler",
    "purchase_date": "2024-12-30T00:00:00.000Z",
    "maintenance_life": 260,
    "expiration_date":"2026-12-30T00:00:00.000Z"
}

###
PUT http://localhost:8090/asset/modify/65c8a34a15f19129dad151c2
content-type: application/json

{
    "asset_code": "ast999E1",
    "asset_name": "Water Cooler",
    "description": "Voltas Water Cooler",
    "purchase_date": "2024-12-30T00:00:00.000Z",
    "maintenance_life": 260,
    "expiration_date":"2026-12-30T00:00:00.000Z"
}
###
GET http://localhost:8090/asset/getAll
###
GET http://localhost:8090/asset/getById/65c8a34a15f19129dad151c2
###
DELETE http://localhost:8090/asset/delete/65c8a34a15f19129dad151c2
###
//End Of Asset


//Allotment
###
POST http://localhost:8090/allotment/add
content-type: application/json

{
    "station_name":"Gorakhpur",
    "station_code":"GKP",
    "asset_code":"ast99",
    "asset_name":"Water Cooler",  
    "description":"Voltas Water Cooler",
    "allotment_date":"2025-12-31T00:00:00.000+00:00",
    "maintenance_due_date":"2026-12-17T00:00:00.000+00:00",
    "expiration_date": "2026-12-30T00:00:00.000+00:00"
}

###
PUT http://localhost:8090/allotment/modify/65c8a3a315f19129dad151c9
content-type: application/json

{
    "station_name":"Gorakhpur",
    "station_code":"GKP",
    "asset_code":"ast99",
    "asset_name":"Water Cooler",  
    "description":"Voltas Water Cooler",
    "allotment_date":"2024-12-31T00:00:00.000+00:00",
    "maintenance_due_date":"2025-12-17T00:00:00.000+00:00",
    "expiration_date": "2026-12-30T00:00:00.000+00:00"
}

###
GET http://localhost:8090/allotment/getAll
###
GET http://localhost:8090/allotment/getById/65c8a3a315f19129dad151c9
###
DELETE http://localhost:8090/allotment/delete/65c70a747cfabf8d855d05a5
###

//End of Allotment 